Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,109 +13,109 @@ concurrency:
   group: ${{ github.head_ref || github.run_id }}
   cancel-in-progress: true
 jobs:
-  build:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-          - macos-latest
-          - ubuntu-20.04
-          - windows-latest
-        host:
-          - x64
-        target:
-          - x64
-        node:
-          - 10
-          - 12
-          - 13
-          - 14
-          - 15
-          - 16
-          - 17
-          - 18
-        include:
-          - os: windows-latest
-            node: 16
-            host: x86
-            target: x86
-          - os: macos-m1
-            node: 16
-            host: arm64
-            target: arm64
-    name: ${{ matrix.os }} (node=${{ matrix.node }}, host=${{ matrix.host }}, target=${{ matrix.target }})
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.node }}
-          architecture: ${{ matrix.host }}
+  # build:
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os:
+  #         - macos-latest
+  #         - ubuntu-20.04
+  #         - windows-latest
+  #       host:
+  #         - x64
+  #       target:
+  #         - x64
+  #       node:
+  #         - 10
+  #         - 12
+  #         - 13
+  #         - 14
+  #         - 15
+  #         - 16
+  #         - 17
+  #         - 18
+  #       include:
+  #         - os: windows-latest
+  #           node: 16
+  #           host: x86
+  #           target: x86
+  #         - os: macos-m1
+  #           node: 16
+  #           host: arm64
+  #           target: arm64
+  #   name: ${{ matrix.os }} (node=${{ matrix.node }}, host=${{ matrix.host }}, target=${{ matrix.target }})
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: actions/setup-node@v3
+  #       with:
+  #         node-version: ${{ matrix.node }}
+  #         architecture: ${{ matrix.host }}
 
-      - name: Add yarn (self-hosted)
-        if: matrix.os == 'macos-m1'
-        run: npm install -g yarn
+  #     - name: Add yarn (self-hosted)
+  #       if: matrix.os == 'macos-m1'
+  #       run: npm install -g yarn
 
-      - name: Add msbuild to PATH
-        uses: microsoft/setup-msbuild@v1.3
-        if: contains(matrix.os, 'windows')
-        with:
-          msbuild-architecture: ${{ matrix.target }}
+  #     - name: Add msbuild to PATH
+  #       uses: microsoft/setup-msbuild@v1.3
+  #       if: contains(matrix.os, 'windows')
+  #       with:
+  #         msbuild-architecture: ${{ matrix.target }}
 
-      - name: Install dependencies
-        run: yarn install --ignore-scripts
+  #     - name: Install dependencies
+  #       run: yarn install --ignore-scripts
 
-      - name: Add env vars
-        shell: bash
-        run: |
-          echo "V=1" >> $GITHUB_ENV
+  #     - name: Add env vars
+  #       shell: bash
+  #       run: |
+  #         echo "V=1" >> $GITHUB_ENV
 
-          if [ "${{ matrix.target }}" = "x86" ]; then
-            echo "TARGET=ia32" >> $GITHUB_ENV
-          else
-            echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
-          fi
+  #         if [ "${{ matrix.target }}" = "x86" ]; then
+  #           echo "TARGET=ia32" >> $GITHUB_ENV
+  #         else
+  #           echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
+  #         fi
 
-      - name: Add Linux env vars
-        if: contains(matrix.os, 'ubuntu')
-        run: |
-          echo "CFLAGS=${CFLAGS:-} -include ../src/gcc-preinclude.h" >> $GITHUB_ENV
-          echo "CXXFLAGS=${CXXFLAGS:-} -include ../src/gcc-preinclude.h" >> $GITHUB_ENV
+  #     - name: Add Linux env vars
+  #       if: contains(matrix.os, 'ubuntu')
+  #       run: |
+  #         echo "CFLAGS=${CFLAGS:-} -include ../src/gcc-preinclude.h" >> $GITHUB_ENV
+  #         echo "CXXFLAGS=${CXXFLAGS:-} -include ../src/gcc-preinclude.h" >> $GITHUB_ENV
 
-      - name: Configure build
-        run: yarn node-pre-gyp configure --target_arch=${{ env.TARGET }}
+  #     - name: Configure build
+  #       run: yarn node-pre-gyp configure --target_arch=${{ env.TARGET }}
 
-      - name: Build binaries
-        run: yarn node-pre-gyp build --target_arch=${{ env.TARGET }}
+  #     - name: Build binaries
+  #       run: yarn node-pre-gyp build --target_arch=${{ env.TARGET }}
 
-      - name: Print binary info
-        if: contains(matrix.os, 'ubuntu')
-        run: |
-          ldd lib/binding/*/node_sqlite3.node
-          echo "---"
-          nm lib/binding/*/node_sqlite3.node | grep "GLIBC_" | c++filt || true
-          echo "---"
-          file lib/binding/napi-v*/*
+  #     - name: Print binary info
+  #       if: contains(matrix.os, 'ubuntu')
+  #       run: |
+  #         ldd lib/binding/*/node_sqlite3.node
+  #         echo "---"
+  #         nm lib/binding/*/node_sqlite3.node | grep "GLIBC_" | c++filt || true
+  #         echo "---"
+  #         file lib/binding/napi-v*/*
 
-      - name: Run tests
-        run: yarn test
+  #     - name: Run tests
+  #       run: yarn test
 
-      - name: Package prebuilt binaries
-        run: yarn node-pre-gyp package --target_arch=${{ env.TARGET }}
+  #     - name: Package prebuilt binaries
+  #       run: yarn node-pre-gyp package --target_arch=${{ env.TARGET }}
 
-      - name: Upload binaries to commit artifacts
-        uses: actions/upload-artifact@v3
-        if: matrix.node == 16
-        with:
-          name: prebuilt-binaries
-          path: build/stage/*/*
-          retention-days: 7
+  #     - name: Upload binaries to commit artifacts
+  #       uses: actions/upload-artifact@v3
+  #       if: matrix.node == 16
+  #       with:
+  #         name: prebuilt-binaries
+  #         path: build/stage/*/*
+  #         retention-days: 7
 
-      - name: Upload binaries to GitHub Release
-        run: yarn node-pre-gyp-github publish
-        if: matrix.node == 16 && startsWith(github.ref, 'refs/tags/')
-        env:
-          NODE_PRE_GYP_GITHUB_TOKEN: ${{ github.token }}
+  #     - name: Upload binaries to GitHub Release
+  #       run: yarn node-pre-gyp-github publish
+  #       if: matrix.node == 16 && startsWith(github.ref, 'refs/tags/')
+  #       env:
+  #         NODE_PRE_GYP_GITHUB_TOKEN: ${{ github.token }}
   build-qemu:
     runs-on: ubuntu-latest
     if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
@@ -125,17 +125,17 @@ jobs:
         node:
           - 18
         target:
-          - linux/arm64
-          - linux/arm/v7
+          # - linux/arm64
+          # - linux/arm/v7
           - linux/arm/v6
         variant:
           - bullseye
           - alpine3.15
-        include:
-          # musl x64 builds
-          - target: linux/amd64
-            variant: alpine3.15
-            node: 18
+        # include:
+        #   # musl x64 builds
+        #   - target: linux/amd64
+        #     variant: alpine3.15
+        #     node: 18
     name: ${{ matrix.variant }} (node=${{ matrix.node }}, target=${{ matrix.target }})
     steps:
       - uses: actions/checkout@v3
